/*
 * lcd_font.h - 16x24 1bpp bitmap font for the LCD UI code, covering
 * printable ASCII. The data in lcd_font.c is generated by
 * tools/gen_lcd_font.py.
 */
#ifndef LCD_FONT_H
#define LCD_FONT_H

#include <stdint.h>

#define LCD_FONT_WIDTH  16
#define LCD_FONT_HEIGHT 24
#define LCD_FONT_FIRST  0x20
#define LCD_FONT_LAST   0x7E

/* One uint16_t per glyph row, MSB = leftmost pixel. Index with
 * (c - LCD_FONT_FIRST). */
extern const uint16_t lcd_font[LCD_FONT_LAST - LCD_FONT_FIRST + 1][LCD_FONT_HEIGHT];

#endif /* LCD_FONT_H */
