if(EXISTS "/home/lachlan-wilson/Documents/University/thesis/dev/tests/test_usage_bitmap[1]_tests.cmake")
  include("/home/lachlan-wilson/Documents/University/thesis/dev/tests/test_usage_bitmap[1]_tests.cmake")
else()
  add_test(test_usage_bitmap_NOT_BUILT test_usage_bitmap_NOT_BUILT)
endif()
