if(EXISTS "/home/lachlan-wilson/Documents/University/thesis/dev/tests/test_db_recovery[1]_tests.cmake")
  include("/home/lachlan-wilson/Documents/University/thesis/dev/tests/test_db_recovery[1]_tests.cmake")
else()
  add_test(test_db_recovery_NOT_BUILT test_db_recovery_NOT_BUILT)
endif()
