#include <gtest/gtest.h>
#include <cstring>
#include <cstdint>

extern "C"
{
#include "usage_bitmap.h"
#include "storage.h"
#include "heap_storage.h"
#include "superheader.h"
}

class UsageBitmapTest : public ::testing::Test
{
protected:

    Storage *storage = &heap_storage;
    HeapStorageContext storage_ctx;

    uint8_t *storage_mem = nullptr;

    /*
     * Storage layout:
     *
     *   Sector 0 ... Superheader
     *   Sector 1 ... Usage bitmap
     *   Sector N ... Data
     *
     * The bitmap itself is rounded up to whole sectors.
     */
    static constexpr uint16_t STORAGE_SECTOR_COUNT =
        SUPERHEADER_SECTOR_SIZE +
        USAGE_BITMAP_SECTOR_SIZE +
        TOTAL_DATA_SECTOR_SIZE;


    void SetUp() override
    {
        /*
         * These should match the values generated by your
         * current implementation.
         */
//         ASSERT_EQ(SUPERHEADER_SECTOR_SIZE, 1);
//         ASSERT_EQ(USAGE_BITMAP_SECTOR_SIZE, 61);
//         ASSERT_EQ(TOTAL_DATA_SECTOR_SIZE, 30969);

        /*
         * Allocate the simulated SD card.
         */
        storage_mem =
            new uint8_t[
                SECTOR_SIZE * STORAGE_SECTOR_COUNT
            ];

        ASSERT_NE(storage_mem, nullptr);

        /*
         * Start with an erased/empty SD card.
         */
        memset(
            storage_mem,
            0,
            SECTOR_SIZE * STORAGE_SECTOR_COUNT
        );

        /*
         * Initialise heap storage.
         */
        ASSERT_TRUE(
            HeapStorage_Init(
                &storage_ctx,
                storage_mem,
                SECTOR_SIZE,
                STORAGE_SECTOR_COUNT
            )
        );

        storage->context = &storage_ctx;

        /*
         * Clear the global bitmap before each test.
         */
        memset(
            usage_bitmap,
            0,
            USAGE_BITMAP_STORAGE_SIZE *
                sizeof(uint32_t)
        );
    }


    void TearDown() override
    {
        delete[] storage_mem;
        storage_mem = nullptr;
    }


    /**
     * @brief Read a complete bitmap sector from the
     *        simulated SD card.
     */
    void read_bitmap_sector(
        uint32_t bitmap_sector,
        uint8_t *buffer)
    {
        ASSERT_NE(buffer, nullptr);

        ASSERT_TRUE(
            storage->read_block(
                storage->context,
                USAGE_BITMAP_START_SECTOR +
                    bitmap_sector,
                buffer
            )
        );
    }


    /**
     * @brief Verify a bitmap sector is completely zero.
     */
    void expect_sector_zero(
        uint32_t bitmap_sector)
    {
        uint8_t buffer[SECTOR_SIZE]{};

        read_bitmap_sector(
            bitmap_sector,
            buffer
        );

        for (uint32_t i = 0; i < SECTOR_SIZE; i++)
        {
            EXPECT_EQ(
                buffer[i],
                0
            );
        }
    }
};


/**
 * @brief Verify the bitmap can be read from the SD card.
 */
TEST_F(UsageBitmapTest, ReadUsageBitmap)
{
    /*
     * Put a known pattern into every bitmap sector
     * on the simulated SD card.
     */
    uint8_t pattern[SECTOR_SIZE];

    memset(
        pattern,
        0xAA,
        sizeof(pattern)
    );

    for (uint32_t sector = 0;
         sector < USAGE_BITMAP_SECTOR_SIZE;
         sector++)
    {
        ASSERT_TRUE(
            storage->write_block(
                storage->context,
                USAGE_BITMAP_START_SECTOR + sector,
                pattern
            )
        );
    }

    /*
     * Read the complete bitmap.
     */
    ASSERT_TRUE(
        read_usage_bitmap(
            storage
        )
    );

    /*
     * Every uint32_t should now contain 0xAAAAAAAA.
     */
    for (uint32_t i = 0;
         i < USAGE_BITMAP_STORAGE_SIZE;
         i++)
    {
        EXPECT_EQ(
            usage_bitmap[i],
            0xAAAAAAAAu
        );
    }
}


/**
 * @brief Verify an unused bit initially reads as false.
 */
TEST_F(UsageBitmapTest, CheckUnusedBit)
{
    EXPECT_FALSE(
        check_usage_bit(0)
    );

    EXPECT_FALSE(
        check_usage_bit(1)
    );

    EXPECT_FALSE(
        check_usage_bit(32)
    );

    EXPECT_FALSE(
        check_usage_bit(4095)
    );

    EXPECT_FALSE(
        check_usage_bit(4096)
    );
}


/**
 * @brief Verify setting a usage bit updates RAM and SD card.
 */
TEST_F(UsageBitmapTest, SetUsageBit)
{
    const uint32_t index = 0;

    ASSERT_TRUE(
        update_usage_bit(
            storage,
            index,
            true
        )
    );

    /*
     * Verify RAM.
     */
    EXPECT_TRUE(
        check_usage_bit(index)
    );

    /*
     * Verify the corresponding SD sector.
     */
    uint8_t result[SECTOR_SIZE]{};

    ASSERT_TRUE(
        storage->read_block(
            storage->context,
            USAGE_BITMAP_START_SECTOR,
            result
        )
    );

    /*
     * Bit 0 of the first uint32_t should be set.
     */
    uint32_t word = 0;

    memcpy(
        &word,
        result,
        sizeof(uint32_t)
    );

    EXPECT_EQ(
        word,
        0x00000001u
    );
}


/**
 * @brief Verify clearing a usage bit updates RAM and SD card.
 */
TEST_F(UsageBitmapTest, ClearUsageBit)
{
    const uint32_t index = 0;

    /*
     * Set the bit first.
     */
    ASSERT_TRUE(
        update_usage_bit(
            storage,
            index,
            true
        )
    );

    EXPECT_TRUE(
        check_usage_bit(index)
    );

    /*
     * Clear the bit.
     */
    ASSERT_TRUE(
        update_usage_bit(
            storage,
            index,
            false
        )
    );

    /*
     * Verify RAM.
     */
    EXPECT_FALSE(
        check_usage_bit(index)
    );

    /*
     * Verify SD card.
     */
    uint8_t result[SECTOR_SIZE]{};

    ASSERT_TRUE(
        storage->read_block(
            storage->context,
            USAGE_BITMAP_START_SECTOR,
            result
        )
    );

    uint32_t word = 0;

    memcpy(
        &word,
        result,
        sizeof(uint32_t)
    );

    EXPECT_EQ(
        word,
        0x00000000u
    );
}


/**
 * @brief Verify all 32 bits of a uint32_t can be used.
 */
TEST_F(UsageBitmapTest, AllBitsInWord)
{
    const uint32_t base_index = 0;

    /*
     * Set every bit in the first word.
     */
    for (uint32_t bit = 0;
         bit < BITS_PER_ELEMENT;
         bit++)
    {
        ASSERT_TRUE(
            update_usage_bit(
                storage,
                base_index + bit,
                true
            )
        );
    }

    /*
     * Every bit should now be set.
     */
    for (uint32_t bit = 0;
         bit < BITS_PER_ELEMENT;
         bit++)
    {
        EXPECT_TRUE(
            check_usage_bit(
                base_index + bit
            )
        );
    }

    /*
     * Read the sector back.
     */
    uint8_t result[SECTOR_SIZE]{};

    ASSERT_TRUE(
        storage->read_block(
            storage->context,
            USAGE_BITMAP_START_SECTOR,
            result
        )
    );

    uint32_t word = 0;

    memcpy(
        &word,
        result,
        sizeof(uint32_t)
    );

    EXPECT_EQ(
        word,
        0xFFFFFFFFu
    );
}


/**
 * @brief Verify bitmap sector boundary at sector 4096.
 *
 * One 512-byte bitmap sector contains:
 *
 *   512 * 8 = 4096 bits
 *
 * Therefore:
 *
 *   data sector 4095 -> bitmap sector 0
 *   data sector 4096 -> bitmap sector 1
 */
TEST_F(UsageBitmapTest, BitmapSectorBoundary)
{
    const uint32_t first_sector_index = 0;
    const uint32_t last_index_sector_0 = 4095;
    const uint32_t first_index_sector_1 = 4096;

    /*
     * Set the final bit represented by bitmap sector 0.
     */
    ASSERT_TRUE( update_usage_bit( storage, last_index_sector_0, true));

    EXPECT_TRUE( check_usage_bit( last_index_sector_0));

    /*
     * Set the first bit represented by bitmap sector 1.
     */
    ASSERT_TRUE( update_usage_bit( storage, first_index_sector_1, true));

    EXPECT_TRUE( check_usage_bit( first_index_sector_1));

    /*
     * Make sure the two bits didn't interfere with each other.
     */
    EXPECT_TRUE( check_usage_bit( last_index_sector_0));

    EXPECT_TRUE( check_usage_bit( first_index_sector_1));

    /*
     * Read bitmap sector 0.
     */
    uint8_t sector0[SECTOR_SIZE]{};

    ASSERT_TRUE( storage->read_block( storage->context, USAGE_BITMAP_START_SECTOR, sector0));

    /*
     * Bit 4095 is:
     *
     * word = 127
     * bit  = 31
     */
    uint32_t word0 = 0;

    memcpy( &word0, &sector0[127 * sizeof(uint32_t)], sizeof(uint32_t));

    EXPECT_EQ( word0, 0x80000000u);


    /*
     * Read bitmap sector 1.
     */
    uint8_t sector1[SECTOR_SIZE]{};

    ASSERT_TRUE( storage->read_block( storage->context, USAGE_BITMAP_START_SECTOR + 1, sector1));

    /*
     * Bit 4096 is:
     *
     * word = 0
     * bit  = 0
     */
    uint32_t word1 = 0;

    memcpy( &word1, sector1, sizeof(uint32_t));

    EXPECT_EQ( word1, 0x00000001u);
}


/**
 * @brief Verify the beginning and end of every bitmap sector.
 */
TEST_F(UsageBitmapTest, EveryBitmapSectorBoundary)
{
    const uint32_t sectors_per_bitmap_sector =
        SECTOR_SIZE * 8;

    for (uint32_t bitmap_sector = 0;
         bitmap_sector < USAGE_BITMAP_SECTOR_SIZE;
         bitmap_sector++)
    {
        uint32_t first_index =
            bitmap_sector *
            sectors_per_bitmap_sector;

        /*
         * Don't go beyond the logical bitmap.
         */
        if (first_index >= TOTAL_DATA_SECTOR_SIZE)
        {
            break;
        }

        uint32_t last_index =
            first_index +
            sectors_per_bitmap_sector -
            1;

        if (last_index >= TOTAL_DATA_SECTOR_SIZE)
        {
            last_index =
                TOTAL_DATA_SECTOR_SIZE - 1;
        }

        /*
         * Set first bit in this bitmap sector.
         */
        ASSERT_TRUE(
            update_usage_bit(
                storage,
                first_index,
                true
            )
        );

        EXPECT_TRUE(
            check_usage_bit(first_index)
        );

        /*
         * Set final bit in this bitmap sector.
         */
        ASSERT_TRUE(
            update_usage_bit(
                storage,
                last_index,
                true
            )
        );

        EXPECT_TRUE(
            check_usage_bit(last_index)
        );

        /*
         * Check that the expected bitmap sector
         * contains the modifications.
         */
        uint8_t result[SECTOR_SIZE]{};

        ASSERT_TRUE(
            storage->read_block(
                storage->context,
                USAGE_BITMAP_START_SECTOR +
                    bitmap_sector,
                result
            )
        );

        /*
         * First bit.
         */
        uint32_t first_word = 0;

        memcpy(
            &first_word,
            result,
            sizeof(uint32_t)
        );

        EXPECT_NE(
            first_word & 0x1u,
            0u
        );

        /*
         * Last bit.
         */
        uint32_t last_word = 0;

        memcpy(
            &last_word,
            &result[127 * sizeof(uint32_t)],
            sizeof(uint32_t)
        );

        /*
         * If this is a complete bitmap sector,
         * the last bit should be bit 31.
         */
        if (last_index - first_index == 4095)
        {
            EXPECT_NE(
                last_word & 0x80000000u,
                0u
            );
        }
    }
}


/**
 * @brief Verify changing one bit does not modify neighbouring bits.
 */
TEST_F(UsageBitmapTest, DoesNotModifyNeighbouringBits)
{
    const uint32_t index = 100;

    /*
     * Set the target bit.
     */
    ASSERT_TRUE(
        update_usage_bit(
            storage,
            index,
            true
        )
    );

    EXPECT_TRUE(
        check_usage_bit(index)
    );

    /*
     * Neighbouring bits should remain clear.
     */
    EXPECT_FALSE(
        check_usage_bit(index - 1)
    );

    EXPECT_FALSE(
        check_usage_bit(index + 1)
    );

    /*
     * Also check the beginning/end of the word.
     */
    EXPECT_FALSE(
        check_usage_bit(96)
    );

    EXPECT_FALSE(
        check_usage_bit(127)
    );
}


/**
 * @brief Verify updating bits in different bitmap sectors
 *        does not overwrite each other.
 */
TEST_F(UsageBitmapTest, MultipleBitmapSectors)
{
    const uint32_t index0 = 0;
    const uint32_t index1 = 4096;
    const uint32_t index2 = 8192;

    ASSERT_TRUE(
        update_usage_bit(
            storage,
            index0,
            true
        )
    );

    ASSERT_TRUE(
        update_usage_bit(
            storage,
            index1,
            true
        )
    );

    ASSERT_TRUE(
        update_usage_bit(
            storage,
            index2,
            true
        )
    );

    EXPECT_TRUE(
        check_usage_bit(index0)
    );

    EXPECT_TRUE(
        check_usage_bit(index1)
    );

    EXPECT_TRUE(
        check_usage_bit(index2)
    );

    /*
     * Check the actual SD sectors.
     */
    uint8_t result[SECTOR_SIZE]{};

    ASSERT_TRUE(
        storage->read_block(
            storage->context,
            USAGE_BITMAP_START_SECTOR,
            result
        )
    );

    uint32_t word0 = 0;

    memcpy(
        &word0,
        result,
        sizeof(uint32_t)
    );

    EXPECT_EQ(
        word0,
        0x00000001u
    );


    ASSERT_TRUE(
        storage->read_block(
            storage->context,
            USAGE_BITMAP_START_SECTOR + 1,
            result
        )
    );

    uint32_t word1 = 0;

    memcpy(
        &word1,
        result,
        sizeof(uint32_t)
    );

    EXPECT_EQ(
        word1,
        0x00000001u
    );


    ASSERT_TRUE(
        storage->read_block(
            storage->context,
            USAGE_BITMAP_START_SECTOR + 2,
            result
        )
    );

    uint32_t word2 = 0;

    memcpy(
        &word2,
        result,
        sizeof(uint32_t)
    );

    EXPECT_EQ(
        word2,
        0x00000001u
    );
}


/**
 * @brief Verify the final valid data sector can be represented.
 */
TEST_F(UsageBitmapTest, LastDataSector)
{
    const uint32_t index =
        TOTAL_DATA_SECTOR_SIZE - 1;

    ASSERT_TRUE(
        update_usage_bit(
            storage,
            index,
            true
        )
    );

    EXPECT_TRUE(
        check_usage_bit(index)
    );

    /*
     * Verify the corresponding bitmap sector.
     */
    const uint32_t bitmap_sector =
        USAGE_BITMAP_FIND_SECTOR(index);

    ASSERT_LT(
        bitmap_sector,
        USAGE_BITMAP_SECTOR_SIZE
    );

    uint8_t result[SECTOR_SIZE]{};

    ASSERT_TRUE(
        storage->read_block(
            storage->context,
            USAGE_BITMAP_START_SECTOR +
                bitmap_sector,
            result
        )
    );

    /*
     * The final bit must be present somewhere in
     * this sector.
     */
    const uint32_t element =
        USAGE_BITMAP_FIND_ELEMENT(index);

    const uint32_t bit =
        USAGE_BITMAP_FIND_BIT(index);

    uint32_t word = 0;

    memcpy(
        &word,
        &result[element * sizeof(uint32_t)],
        sizeof(uint32_t)
    );

    EXPECT_NE(
        word & (1U << bit),
        0u
    );
}


/**
 * @brief Verify repeated set/clear operations.
 */
TEST_F(UsageBitmapTest, RepeatedSetClear)
{
    const uint32_t index = 12345;

    for (int i = 0; i < 100; i++)
    {
        ASSERT_TRUE(
            update_usage_bit(
                storage,
                index,
                true
            )
        );

        EXPECT_TRUE(
            check_usage_bit(index)
        );

        ASSERT_TRUE(
            update_usage_bit(
                storage,
                index,
                false
            )
        );

        EXPECT_FALSE(
            check_usage_bit(index)
        );
    }
}

TEST_F(UsageBitmapTest, WordBoundary)
{
    const uint32_t indices[] = {
        31, 32,
        63, 64,
        95, 96,
        127, 128
    };

    for (uint32_t index : indices)
    {
        ASSERT_TRUE(
            update_usage_bit(storage, index, true)
        );

        EXPECT_TRUE(check_usage_bit(index));
    }

    /*
     * Make sure setting bit 32 didn't affect bit 31,
     * etc.
     */
    EXPECT_TRUE(check_usage_bit(31));
    EXPECT_TRUE(check_usage_bit(32));
    EXPECT_TRUE(check_usage_bit(63));
    EXPECT_TRUE(check_usage_bit(64));
    EXPECT_TRUE(check_usage_bit(95));
    EXPECT_TRUE(check_usage_bit(96));
    EXPECT_TRUE(check_usage_bit(127));
    EXPECT_TRUE(check_usage_bit(128));
}


/**
 * @brief Stress test every data-sector index.
 *
 * Every valid bitmap bit is set and then cleared.
 * This exercises all word and sector boundaries.
 */
TEST_F(UsageBitmapTest, EveryDataSector)
{
    /*
     * Set every bit.
     */
    for (uint32_t index = 0;
         index < TOTAL_DATA_SECTOR_SIZE;
         index++)
    {
        ASSERT_TRUE(
            update_usage_bit(
                storage,
                index,
                true
            )
        );

        ASSERT_TRUE(
            check_usage_bit(index)
        );
    }

    /*
     * Verify every bit is set.
     */
    for (uint32_t index = 0;
         index < TOTAL_DATA_SECTOR_SIZE;
         index++)
    {
        EXPECT_TRUE(
            check_usage_bit(index)
        );
    }

    /*
     * Clear every bit.
     */
    for (uint32_t index = 0;
         index < TOTAL_DATA_SECTOR_SIZE;
         index++)
    {
        ASSERT_TRUE(
            update_usage_bit(
                storage,
                index,
                false
            )
        );

        ASSERT_FALSE(
            check_usage_bit(index)
        );
    }

    /*
     * Verify every bit is clear.
     */
    for (uint32_t index = 0;
         index < TOTAL_DATA_SECTOR_SIZE;
         index++)
    {
        EXPECT_FALSE(
            check_usage_bit(index)
        );
    }
}
