if(EXISTS "/home/lachlan-wilson/Documents/University/thesis/dev/tests/test_hash_table[1]_tests.cmake")
  include("/home/lachlan-wilson/Documents/University/thesis/dev/tests/test_hash_table[1]_tests.cmake")
else()
  add_test(test_hash_table_NOT_BUILT test_hash_table_NOT_BUILT)
endif()
