if(EXISTS "/home/lachlan-wilson/Documents/University/thesis/dev/tests/test_ring_buffer[1]_tests.cmake")
  include("/home/lachlan-wilson/Documents/University/thesis/dev/tests/test_ring_buffer[1]_tests.cmake")
else()
  add_test(test_ring_buffer_NOT_BUILT test_ring_buffer_NOT_BUILT)
endif()
