if(EXISTS "/home/lachlan-wilson/Documents/University/thesis/dev/tests/test_sector_crc[1]_tests.cmake")
  include("/home/lachlan-wilson/Documents/University/thesis/dev/tests/test_sector_crc[1]_tests.cmake")
else()
  add_test(test_sector_crc_NOT_BUILT test_sector_crc_NOT_BUILT)
endif()
