#!/usr/bin/env python3
"""
gen_lcd_font.py - rasterise a monospace TTF into the 1bpp bitmap font used by
the LCD UI code (source/app/src/lcd_font.c).

Each glyph is LCD_FONT_WIDTH x LCD_FONT_HEIGHT pixels, stored as one
uint16_t per row with the MSB as the leftmost pixel. Covers printable ASCII
(0x20-0x7E).

Usage:
    python3 tools/gen_lcd_font.py [font.ttf] > source/app/src/lcd_font.c
"""
import sys

from PIL import Image, ImageDraw, ImageFont

WIDTH = 16
HEIGHT = 24
FONT_SIZE = 22
FIRST, LAST = 0x20, 0x7E
DEFAULT_TTF = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"


def render(font, ch):
    img = Image.new("1", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(img)
    # Centre the advance box horizontally, and centre cap-top..descender
    # vertically so every glyph shares a baseline and nothing is clipped.
    advance = font.getlength(ch)
    cap_top = font.getbbox("H")[1]
    desc_bottom = font.getbbox("gjpqy")[3]
    x = (WIDTH - advance) / 2
    y = (HEIGHT - (desc_bottom - cap_top)) // 2 - cap_top
    draw.text((x, y), ch, font=font, fill=1)
    rows = []
    for py in range(HEIGHT):
        bits = 0
        for px in range(WIDTH):
            if img.getpixel((px, py)):
                bits |= 1 << (WIDTH - 1 - px)
        rows.append(bits)
    return rows


def main():
    ttf = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_TTF
    font = ImageFont.truetype(ttf, FONT_SIZE)

    print("/*")
    print(" * lcd_font.c - GENERATED by tools/gen_lcd_font.py, do not edit.")
    print(f" * Source font: {ttf.rsplit('/', 1)[-1]} @ {FONT_SIZE}px.")
    print(" */")
    print('#include "lcd_font.h"')
    print()
    print("const uint16_t lcd_font[LCD_FONT_LAST - LCD_FONT_FIRST + 1][LCD_FONT_HEIGHT] = {")
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        rows = render(font, ch)
        label = "space" if ch == " " else ("backslash" if ch == "\\" else ch)
        body = ", ".join(f"0x{r:04X}" for r in rows)
        print(f"    /* 0x{code:02X} {label} */ {{{body}}},")
    print("};")


if __name__ == "__main__":
    main()
